# Файл: docker-compose.yml
version: '3.8'

services:
  # 1. Основной контейнер с веб-сайтом (Запускается по умолчанию)
  analyzer-web:
    build:
      context: ..
      dockerfile: AIAnalyzer/Dockerfile
    ports:
      - "8080:8080"

  # 2. Опциональный контейнер с сервером ИИ (Скрыт за профилем)
  ollama-server:
    image: ollama/ollama:latest
    container_name: aianalyzer-ollama-server-1
    ports:
      - "11434:11434"
    profiles:
      - manual-ai # <-- ВОТ ГЛАВНАЯ МАГИЯ! Этот контейнер теперь игнорируется при обычном запуске
    volumes:
      # Магия здесь: делимся папкой Олламы из Windows внутрь Linux-контейнера
      - C:\Users\LittleSangwoo\.ollama:/root/.ollama

